import Navbar from "./Components/Navbar";
import Sidebar from "./Components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import styles from './page.module.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
        <div className={styles.content}>
          <div className={styles.sidebar}>
            <Sidebar />
          </div>
          <div className={styles.feed}>
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
